### ISSUE TITLE
how do i host this

### ISSUE THREAD

**Issue by shihaamabr** [WhoIsFishie/Fishie-Honesty-UI#4]
where is the Dockerfile?

**Comment by WovenCoast** [comment]
it is your job to make it

**Comment by shihaamabr** [comment]
`7770000014728` 
 mvr 195 (magey roadha veehlun miadhu)

**Comment by WovenCoast** [comment]
![BML_RECEIPT_1680937796511](https://user-images.githubusercontent.com/44475239/230708531-3afe475c-366c-4f99-ae1a-73ec238168e5.jpg)

**Comment by athphane** [comment]
It's that easy huh

**Comment by shihaamabr** [comment]
https://github.com/WhoIsFishie/Fishie-Honesty-UI/commit/8425b8fb67b8095516a1641d8f8fadc63c97f8c2


youre welcome
